//go:build ignore
// +build ignore

package main

import (
	"bufio"
	"bytes"
	"fmt"
	"log"
	"os"
	"strings"
	"text/template"
)

// headerKV holds a parsed key-value pair from protocol.conf.
type headerKV struct {
	Key      string // e.g. "ProtocolRequestIDKey"
	Value    string // e.g. `"X-Request-ID"`
	Internal bool   // true if key starts with "Internal"
}

// 定义生成代码的模板
const goTmpl = `// Code generated by go generate; DO NOT EDIT.
package protocol

// 与网关交互的常量定义表
const (
{{- range . }}
	{{ .Key }} = {{ .Value }}
{{- end }}
)
`

const luaTmpl = `-- Code generated by go generate; DO NOT EDIT.
-- Lua counterpart of internal/protocol/protocol.conf
-- Vendor this file into the tavern-gateway repository.

local _M = {}

{{- range . }}
_M.{{ .Key }} = {{ .Value }}
{{- end }}

_M.FlagOn  = "1"
_M.FlagOff = "0"

-- All internal (TR-*) headers — for sanitization/stripping at the gateway layer.
_M.INTERNAL_HEADERS = {
{{- range . }}{{ if .Internal }}
	{{ .Value }},
{{- end }}{{ end }}
}

return _M
`

func main() {
	// 1. 读取 protocol.conf 文件
	file, err := os.Open("protocol.conf")
	if err != nil {
		log.Fatalf("无法打开 protocol.conf: %v", err)
	}
	defer file.Close()

	var kvs []headerKV
	scanner := bufio.NewScanner(file)

	// 2. 逐行读取、解析 key = value
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}

		kv, err := parseLine(line)
		if err != nil {
			log.Fatalf("解析行失败 %q: %v", line, err)
		}
		kvs = append(kvs, kv)
	}

	if err := scanner.Err(); err != nil {
		log.Fatalf("读取文件错误: %v", err)
	}

	// 3. 渲染 Go 模板
	goT := template.Must(template.New("go").Parse(goTmpl))
	var goBuf bytes.Buffer
	if err := goT.Execute(&goBuf, kvs); err != nil {
		log.Fatalf("Go 模板渲染失败: %v", err)
	}

	// 4. 渲染 Lua 模板
	luaT := template.Must(template.New("lua").Parse(luaTmpl))
	var luaBuf bytes.Buffer
	if err := luaT.Execute(&luaBuf, kvs); err != nil {
		log.Fatalf("Lua 模板渲染失败: %v", err)
	}

	// 5. 写入 protocol_generated.go
	if err := os.WriteFile("protocol_generated.go", goBuf.Bytes(), 0644); err != nil {
		log.Fatalf("Go 文件写入失败: %v", err)
	}

	// 6. 写入 protocol.lua
	if err := os.WriteFile("protocol.lua", luaBuf.Bytes(), 0644); err != nil {
		log.Fatalf("Lua 文件写入失败: %v", err)
	}

	fmt.Println("成功从 protocol.conf 生成 protocol_generated.go 和 protocol.lua")
}

// parseLine parses a line like `KeyName = "Value"` into a headerKV.
func parseLine(line string) (headerKV, error) {
	parts := strings.SplitN(line, "=", 2)
	if len(parts) != 2 {
		return headerKV{}, fmt.Errorf("expected key = value format")
	}

	key := strings.TrimSpace(parts[0])
	value := strings.TrimSpace(parts[1])

	if key == "" || value == "" {
		return headerKV{}, fmt.Errorf("key or value is empty")
	}

	return headerKV{
		Key:      key,
		Value:    value,
		Internal: strings.HasPrefix(key, "Internal"),
	}, nil
}
