//go:build ignore
// +build ignore

package main

import (
	"bufio"
	"bytes"
	"fmt"
	"log"
	"os"
	"strings"
	"text/template"
)

// 定义生成代码的模板
const tmpl = `// Code generated by go generate; DO NOT EDIT.
package protocol

// 与网关交互的常量定义表
const (
{{- range . }}
	{{ . }}
{{- end }}
)
`

func main() {
	// 1. 读取 protocol.conf 文件
	file, err := os.Open("protocol.conf")
	if err != nil {
		log.Fatalf("无法打开 protocol.conf: %v", err)
	}
	defer file.Close()

	var lines []string
	scanner := bufio.NewScanner(file)

	// 2. 逐行读取并过滤空行
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line != "" {
			lines = append(lines, line)
		}
	}

	if err := scanner.Err(); err != nil {
		log.Fatalf("读取文件错误: %v", err)
	}

	// 3. 渲染模板
	t := template.Must(template.New("consts").Parse(tmpl))
	var buf bytes.Buffer
	err = t.Execute(&buf, lines)
	if err != nil {
		log.Fatalf("模板渲染失败: %v", err)
	}

	// 4. 写入到生成的 go 文件中
	err = os.WriteFile("protocol_generated.go", buf.Bytes(), 0644)
	if err != nil {
		log.Fatalf("文件写入失败: %v", err)
	}

	fmt.Println("成功从 protocol.conf 生成 protocol_generated.go")
}
