// Code generated by go generate; DO NOT EDIT.
package protocol

// 与网关交互的常量定义表
const (
	ProtocolRequestIDKey = "X-Request-ID"
	ProtocolCacheStatusKey = "X-Cache"
	ProtocolForceStoreMemory = "X-FS-Mem"
	ProtocolPrefetchCacheKey = "X-Prefetch"
	ProtocolCacheTime = "X-CacheTime"
	InternalLayerKey = "TR-LAYER"
	InternalTraceKey = "TR-TRACE"
	InternalStoreUrl = "TR-STOREURL"
	InternalSwapfile = "TR-SWAPFILE"
	InternalFillRangePercent = "TR-FP"
	InternalCacheErrCode = "TR-ERRCODE"
	InternalUpstreamAddr = "TR-UPS-ADDR"
)
