-- Code generated by go generate; DO NOT EDIT.
-- Lua counterpart of internal/protocol/protocol.conf
-- Vendor this file into the tavern-gateway repository.

local _M = {}
_M.ProtocolRequestIDKey = "X-Request-ID"
_M.ProtocolCacheStatusKey = "X-Cache"
_M.ProtocolForceStoreMemory = "X-FS-Mem"
_M.ProtocolPrefetchCacheKey = "X-Prefetch"
_M.ProtocolCacheTime = "X-CacheTime"
_M.InternalLayerKey = "TR-LAYER"
_M.InternalTraceKey = "TR-TRACE"
_M.InternalStoreUrl = "TR-STOREURL"
_M.InternalSwapfile = "TR-SWAPFILE"
_M.InternalFillRangePercent = "TR-FP"
_M.InternalCacheErrCode = "TR-ERRCODE"
_M.InternalUpstreamAddr = "TR-UPS-ADDR"

_M.FlagOn  = "1"
_M.FlagOff = "0"

-- All internal (TR-*) headers — for sanitization/stripping at the gateway layer.
_M.INTERNAL_HEADERS = {
	"TR-LAYER",
	"TR-TRACE",
	"TR-STOREURL",
	"TR-SWAPFILE",
	"TR-FP",
	"TR-ERRCODE",
	"TR-UPS-ADDR",
}

return _M
