{
 "title": "Tavern-Cache",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Host",
    "query": {
     "query": "label_values(tr_tavern_go_info,instance)"
    }
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "process memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "tr_tavern_process_resident_memory_bytes{instance=~\"^($instance)$\"}",
     "legendFormat": "{{job}} - resident"
    },
    {
     "expr": "tr_tavern_process_virtual_memory_bytes{instance=~\"^($instance)$\"}",
     "legendFormat": "{{job}} - virtual"
    }
   ]
  },
  {
   "title": "process memory deriv",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "deriv(tr_tavern_process_resident_memory_bytes{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{job}} - resident"
    },
    {
     "expr": "deriv(tr_tavern_process_virtual_memory_bytes{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{job}} - virtual"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(tr_tavern_go_memstats_alloc_bytes{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{job}} - bytes allocated"
    },
    {
     "expr": "rate(tr_tavern_go_memstats_alloc_bytes_total{instance=~\"$instance\"}[30s])",
     "legendFormat": "{{job}} - alloc rate"
    },
    {
     "expr": "tr_tavern_go_memstats_stack_inuse_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{job}} - stack inuse"
    },
    {
     "expr": "tr_tavern_go_memstats_heap_inuse_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{job}} - heap inuse"
    }
   ]
  },
  {
   "title": "go memstats deriv",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "deriv(tr_tavern_go_memstats_alloc_bytes{instance=~\"^($instance)$\"}[$interval])",
     "legendFormat": "{{job}} - bytes allocated"
    },
    {
     "expr": "rate(tr_tavern_go_memstats_alloc_bytes_total{instance=~\"^($instance)$\"}[$interval])",
     "legendFormat": "{{job}} - alloc rate"
    },
    {
     "expr": "deriv(tr_tavern_go_memstats_stack_inuse_bytes{instance=~\"^($instance)$\"}[$interval])",
     "legendFormat": "{{job}} - stack inuse"
    },
    {
     "expr": "deriv(tr_tavern_go_memstats_heap_inuse_bytes{instance=~\"^($instance)$\"}[$interval])",
     "legendFormat": "{{job}} - heap inuse"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tr_tavern_process_open_fds{instance=~\"^($instance)$\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "open fds deriv",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "deriv(tr_tavern_process_open_fds{instance=~\"^($instance)$\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "timeseries",
   "description": "Average number of live memory objects across all instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(job)(tr_tavern_go_memstats_mallocs_total{instance=~\"$instance\"} - tr_tavern_go_memstats_frees_total{instance=~\"$instance\"})",
     "legendFormat": "{{job}}: object count (avg)"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tr_tavern_go_goroutines{instance=~\"^($instance)$\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "GC min & max duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg by (job)(tr_tavern_go_gc_duration_seconds{job=\"tavern\", instance=~\"$instance\",quantile=\"0.0\"})",
     "legendFormat": "{{job}}: min gc time (avg)"
    },
    {
     "expr": "avg by (job)(tr_tavern_go_gc_duration_seconds{job=\"tavern\", instance=~\"$instance\",quantile=\"1.0\"})",
     "legendFormat": "{{job}}: max gc time (avg)"
    }
   ]
  },
  {
   "title": "Next GC, Bytes",
   "type": "timeseries",
   "description": "The number used bytes at which the runtime plans to perform the next GC, averaged across all instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (job)(tr_tavern_go_memstats_next_gc_bytes{job=\"tavern\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}: next gc bytes (avg)"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "req/sec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(tr_tavern_requests_code_total{instance=\"$instance\", code=~\"200|206\"}[$interval]))",
     "legendFormat": "2xx"
    }
   ]
  },
  {
   "title": "HTTP Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum by(code) (increase(tr_tavern_requests_code_total{instance=\"$instance\"}[$interval]))",
     "legendFormat": "HTTP {{code}}"
    }
   ]
  },
  {
   "title": "Unexpected Closed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "increase(tr_tavern_requests_unexpected_closed_total{instance=\"$instance\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "PURGE jobs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "increase(tr_tavern_purge_requests_total{instance=\"$instance\"}[$__interval])",
     "legendFormat": "{{code}}"
    }
   ]
  },
  { "title": "IndexMetric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "WAL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(tavern_pebble_wal_bytes_written_total{instance=\"$instance\"}[1m])",
     "legendFormat": "wal_bytes_written_total"
    },
    {
     "expr": "rate(tavern_pebble_wal_bytes_in_total{instance=\"$instance\"}[1m])",
     "legendFormat": "wal_bytes_in_total"
    },
    {
     "expr": "tavern_pebble_table_backing_size_bytes{instance=\"$instance\"}",
     "legendFormat": "backing_size"
    }
   ]
  },
  {
   "title": "MemTable",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "tavern_pebble_memtable_size_bytes{instance=\"$instance\"}",
     "legendFormat": "memtable_size"
    }
   ]
  }
 ]
}